name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          name: Adelois/remote_tests     
          ref: refs/heads/release
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
